# Generated by Django 4.2 on 2024-10-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('hg_per_ha_yield', models.FloatField()),
                ('average_rain_fall', models.FloatField()),
                ('pesticides_tonnes', models.FloatField()),
                ('avg_temp', models.FloatField()),
            ],
        ),
    ]
