# Generated by Django 5.1.2 on 2024-10-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture_project', '0003_review_status_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='No comment provided'),
        ),
    ]
