# Generated by Django 4.2 on 2024-10-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_technique', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_application', models.DateField()),
                ('impact_rendement', models.FloatField()),
                ('cultures_associees', models.ManyToManyField(to='Culture.cultureagricole')),
            ],
        ),
    ]
