# Generated by Django 5.1.2 on 2024-10-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesticide',
            old_name='Item',
            new_name='item',
        ),
    ]
