# Generated by Django 4.2 on 2024-10-29 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du fournisseur')),
                ('type_fournisseur', models.CharField(choices=[('importateur', 'Importateur'), ('grossiste', 'Grossiste'), ('entreprise_prive', 'Entreprise Privée'), ('cooperative_agricole', 'Coopérative Agricole')], max_length=20, verbose_name='Type de fournisseur')),
                ('adresse', models.TextField(verbose_name='Adresse du fournisseur')),
                ('numero_telephone', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('ressources_fournies', models.TextField(verbose_name='Ressources fournies')),
                ('quantite_disponible', models.FloatField(default=0, verbose_name='Quantité disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ressource', models.CharField(max_length=100, verbose_name='Nom de la ressource')),
                ('type_ressource', models.CharField(choices=[('eau', 'Eau'), ('engrais', 'Engrais'), ('pesticide', 'Pesticide'), ('carburant', 'Carburant'), ('semences', 'Semences')], max_length=50, verbose_name='Type de ressource')),
                ('quantite', models.FloatField(verbose_name='Quantité disponible')),
                ('unite_mesure', models.CharField(max_length=20, verbose_name='Unité de mesure')),
                ('zone', models.CharField(max_length=100, verbose_name='Zone d’application')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RessourceEntity.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='FournisseurRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.FloatField(default=0, verbose_name='Quantité disponible')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RessourceEntity.fournisseur')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RessourceEntity.ressource')),
            ],
            options={
                'unique_together': {('fournisseur', 'ressource')},
            },
        ),
    ]
