# Generated by Django 4.2 on 2024-10-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RessourceEntity', '0002_fournisseur_ressource_nom_ressource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseurressource',
            name='quantite_disponible',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='quantite_disponible',
            field=models.FloatField(default=0, verbose_name='Quantité disponible'),
        ),
    ]
