# Generated by Django 5.1.2 on 2024-10-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDeSol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTypeSol', models.CharField(max_length=50)),
                ('texture', models.CharField(blank=True, max_length=50, null=True)),
                ('profondeur', models.CharField(blank=True, max_length=50, null=True)),
                ('pH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('capacite_retenue_eau', models.CharField(blank=True, max_length=50, null=True)),
                ('nutriments_disponibles', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneGeographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomZone', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('annee', models.PositiveIntegerField()),
                ('temperatureMoyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pluviometrie', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_de_sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonegéosamarapp.typedesol')),
            ],
        ),
    ]
