# Generated by Django 5.1.2 on 2024-10-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZoneGeographique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomZone", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("annee", models.PositiveIntegerField()),
                (
                    "temperatureMoyenne",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("pluviometrie", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
