# Generated by Django 5.1.2 on 2024-10-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonegéosamarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedesol',
            name='capacite_retenue_eau',
            field=models.CharField(blank=True, choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High'), ('Extreme', 'Extreme'), ('Saturated', 'Saturated'), ('Variable', 'Variable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='typedesol',
            name='nutriments_disponibles',
            field=models.CharField(blank=True, choices=[('Nitrogen, Phosphorus', 'Nitrogen, Phosphorus'), ('Potassium, Calcium', 'Potassium, Calcium'), ('Magnesium, Sulfur', 'Magnesium, Sulfur'), ('Iron, Zinc', 'Iron, Zinc'), ('Copper, Manganese', 'Copper, Manganese'), ('Boron, Molybdenum', 'Boron, Molybdenum'), ('Calcium, Magnesium', 'Calcium, Magnesium'), ('Organic Matter', 'Organic Matter')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='typedesol',
            name='profondeur',
            field=models.CharField(blank=True, choices=[('5 cm', '5 cm'), ('10 cm', '10 cm'), ('15 cm', '15 cm'), ('20 cm', '20 cm'), ('25 cm', '25 cm'), ('30 cm', '30 cm'), ('35 cm', '35 cm'), ('40 cm', '40 cm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='typedesol',
            name='texture',
            field=models.CharField(blank=True, choices=[('Grainy', 'Grainy'), ('Clayey', 'Clayey'), ('Loamy', 'Loamy'), ('Silty', 'Silty'), ('Sandy', 'Sandy'), ('Peaty', 'Peaty'), ('Chalky', 'Chalky'), ('Saline', 'Saline')], max_length=50, null=True),
        ),
    ]
