# Generated by Django 5.1.2 on 2024-10-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_culture_id_alter_culture_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RainfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('average_rainfall', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('yield_hg_per_ha', models.FloatField()),
                ('average_rainfall', models.FloatField()),
                ('pesticides_used', models.FloatField()),
                ('avg_temp', models.FloatField()),
            ],
        ),
    ]
